using  cuda
obses: 12116 samples: 115667
north: 23627
south: 25470
west : 24334
east : 26607
bcity: 3543
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    main(vars(config))
  File "main.py", line 20, in main
    train(config)
  File "/home/l/liuxiao/CS5446_Project/my-works/conv_autoencoder/train.py", line 105, in train
    print(f'{c_actions[value]:^5}: {count:>3}')
IndexError: list index out of range
using  cuda
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    main(vars(config))
  File "main.py", line 20, in main
    train(config)
  File "/home/l/liuxiao/CS5446_Project/my-works/conv_autoencoder/train.py", line 113, in train
    num_epochs=num_epochs, device=device, save_every=save_every)
  File "/home/l/liuxiao/CS5446_Project/my-works/conv_autoencoder/train.py", line 33, in train_model
    x = states * distance_m * map_m
RuntimeError: The size of tensor a (21) must match the size of tensor b (64) at non-singleton dimension 1
using  cuda
torch.Size([64, 21, 32, 32]) torch.Size([64, 32, 32]) torch.Size([64, 32, 32])
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    main(vars(config))
  File "main.py", line 20, in main
    train(config)
  File "/home/l/liuxiao/CS5446_Project/my-works/conv_autoencoder/train.py", line 114, in train
    num_epochs=num_epochs, device=device, save_every=save_every)
  File "/home/l/liuxiao/CS5446_Project/my-works/conv_autoencoder/train.py", line 34, in train_model
    x = states * distance_m * map_m
RuntimeError: The size of tensor a (21) must match the size of tensor b (64) at non-singleton dimension 1
using  cuda
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    main(vars(config))
  File "main.py", line 20, in main
    train(config)
  File "/home/l/liuxiao/CS5446_Project/my-works/conv_autoencoder/train.py", line 114, in train
    num_epochs=num_epochs, device=device, save_every=save_every)
  File "/home/l/liuxiao/CS5446_Project/my-works/conv_autoencoder/train.py", line 34, in train_model
    x = states * distance_m * map_m
RuntimeError: The size of tensor a (21) must match the size of tensor b (64) at non-singleton dimension 1
using  cuda
Traceback (most recent call last):
  File "main.py", line 24, in <module>
    main(vars(config))
  File "main.py", line 20, in main
    train(config)
  File "/home/l/liuxiao/CS5446_Project/my-works/conv_autoencoder/train.py", line 114, in train
    num_epochs=num_epochs, device=device, save_every=save_every)
  File "/home/l/liuxiao/CS5446_Project/my-works/conv_autoencoder/train.py", line 34, in train_model
    x = states * distance_m * map_m
RuntimeError: The size of tensor a (21) must match the size of tensor b (64) at non-singleton dimension 1
using  cuda
Epoch 1/2 | train | Loss: 502955004457864470200320.0000
Epoch 1/2 |  val  | Loss: 467983315105703656423424.0000
Epoch 2/2 | train | Loss: 346993548594039274602496.0000
Epoch 2/2 |  val  | Loss: 250132744196470146596864.0000
Work Done.
using  cuda
Epoch 1/2 | train | Loss: 96269783910070416.0000
Epoch 1/2 |  val  | Loss: 95938659631892016.0000
Epoch 2/2 | train | Loss: 82587557279534320.0000
Epoch 2/2 |  val  | Loss: 70894035408846792.0000
Work Done.
